### ISSUE TITLE
The min() function return value in scientific format

### ISSUE THREAD

**Issue by albinth12** [octomix/josson#13]
For the model 
[
  {
    "request_amount": 1000,
    "request_currency": "INR",
    "value_date": "2023-09-04"
  },
  {
    "request_amount": 1001,
    "request_currency": "INR",
    "value_date": "2023-09-04"
    }
]

when finding max(),min() and sum() for request_amount field the min() function return minimum value in scientific format.The max() and sum() returning in the correct format.

output log

 total amount calculated 2001.0
 maximum amount 1001
minimum amount 1E+3

code 
new BigDecimal(josson.getNode("request_amount.sum()").asText());
        log.debug("maximum amount {}", josson.getString("request_amount.max()"));
        log.debug("minimum amount {}", josson.getString("request_amount.min()"));

**Comment by octomix** [comment]
it is strange that my testing output is `1000` instead of `1E+3`.  I've tested with different version of JDK, all output `1000`.

How about function `getInteger()`?
```
josson.getInteger("request_amount.min()")
```

**Comment by albinth12** [comment]
I am using jdk17 .The getIntger() will not helpfull because it's an amount field which can hold a large amount value

**Comment by octomix** [comment]
It may be Jackson ObjectMapper issue.  Please try this statement to setup first:
```
Mapper.mapper()
        .enable(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS)
        .enable(JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN);
```

BTW, it is bad idea to convert number to String and then back to BigDecimal. Maybe you can use:
```
BigDecimal result = BigDecimal.valueOf(josson.getDouble("request_amount.sum()"));
BigDecimal max = BigDecimal.valueOf(josson.getDouble("request_amount.max()"));
BigDecimal min = BigDecimal.valueOf(josson.getDouble("request_amount.min()"));
```

In addition, I think function distinct() is not necessary before you get the first array element. i.e.:
```
String date = josson.getString("[0].value_date");
String currency = josson.getString("[0].request_currency");
```
